mode: medium_00
plan_list:
- - 2.0
  - 15.0
  - -0.3
  - 0
  - 0
  - "2024_07_09_14_25_36"
  - ConstantPlanner
  - {}
load_HD_map: false
start_euler:
- 0.0
- 0.0
- 0.0
start_ab:
- 0.0
- 0.0
start_velo: 1
start_steer: 0
scene_name: scene-0383
iteration: 30000